title: Power-grid frequency database
repository: LRydin/Power-Grid-Frequency
baseurl: /
permalink: '/:title/'
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt"

footer:
  tagline: Power-grid frequency recordings database
  content: '&copy; Leonardo Rydin Gorjão and Benjamin Schäfer'
  #links:
  #  - text: Made with Jekyll
  #    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-include-cache

#search: true
#search_full_content: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - netlify.toml
  - "vendor"
  - "package.json"
